version: "3"

services:
  proxyserver:
    depends_on:
      - app
    image: nginx:latest
    container_name: proxy 
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  app:
    build: 
      context: ./teen/build/libs
      dockerfile: Dockerfile
    container_name: myspring
    restart: always


