spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: singsiuk
    url: jdbc:mysql://localhost:3306/Memo
    password: ssw0304

  thymeleaf:
    cache: 'false'


  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'


server:
  port: '80'


  spring:
    servlet:
      multipart:
        file-size-threshold: 10MB
        location: /Users/mac/Desktop/Desktop-SungMak/00And/memoServer/image
        max-file-size: 20MB
        max-request-size: 200MB

uploadlocation: /Users/mac/Desktop/Desktop-SungMak/00And/memoServer/src/main/resources/static/upload




#spring.servlet.multipart.enabled: 멀티파트 업로드 지원여부 (default: true)
#
#spring.servlet.multipart.file-size-threshold: 파일이 메모리에 기록되는 임계값 (default: 0B)
#
#spring.servlet.multipart.location: 업로드된 파일의 임시 저장 공간
#
#spring.servlet.multipart.max-file-size: 파일의 최대 사이즈 (default: 1MB)
#
#spring.servlet.multipart.max-request-size: 요청의 최대 사이즈 (default: 10MB)
